- name: Install chezmoi
  command: snap install chezmoi --classic
  become: yes
- name: init chezmoi repository
  command:
    cmd: chezmoi init git@github.com:Purrrrrr/settings.git
    creates: ~/.local/share/chezmoi
- name: apply chezmoi repository
  command: chezmoi apply
  when: "'dotfiles-apply' in userChoices"
- name: Install all (n)vim plugins
  command: vim +'PlugInstall --sync' +qa
  when: "'dotfiles-apply' in userChoices"
