- name: Install chezmoi
  command: snap install chezmoi --classic
  become: yes
- name: init chezmoi repository
  command:
    cmd: chezmoi init https://github.com/Purrrrrr/settings.git
    creates: ~/.local/share/chezmoi
- name: Create/insert dotfiles with chezmoi
  when: "'dotfiles-apply' in userChoices"
  block:
  - name: Ensures chezmoi config dir exists
    file: path=~/.config/chezmoi state=directory
  - name: Install chezmoi configuration
    template:
      src: files/chezmoi.toml.j2
      dest: ~/.config/chezmoi/chezmoi.toml
      mode: '0600'
  - name: apply chezmoi repository
    command: chezmoi apply
  - name: Install all (n)vim plugins
    command: nvim +'PlugInstall --sync' +qa
    when: "Neovim" in userChoices
