- name: Install chezmoi
  command: snap install chezmoi --classic
  become: yes
- name: init chezmoi repository
  file:
    dest: ~/.local/share/chezmoi
    src: ~/settings/chezmoi
    state: link
- name: Create/insert dotfiles with chezmoi
  when: "'dotfiles-apply' in userChoices"
  block:
  - name: Ensures chezmoi config dir exists
    file: path=~/.config/chezmoi state=directory
  - name: apply chezmoi repository
    command: chezmoi apply
  - name: Install neovim python support
    command: pip install neovim
    when: '"Neovim" in userChoices'
  - name: Install NVChad 
    git:
      repo: git@github.com:Purrrrrr/nvchad-config.git
      dest: ~/.config/nvim
      clone: yes
      update: ye
    when: '"Neovim" in userChoices'
