- name: Install packages required by XMonad config
  become: yes
  apt:
    state: present
    name:
    - at
    - conky
    - dzen2
    - xmonad
    - suckless-tools
    - wmctrl
    - xcompmgr
    - xdotool
