---
- hosts: localhost
  connection: local
  become_exe: sudo.ws
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - vars.json
  tasks:
    - name: Install required tool packages
      apt:
        state: present
        name:
          - git
          - git-delta
          - net-tools
          - curl
          - wget
          - openssh-client
          - moreutils
          - build-essential
          - screen
          - traceroute
          - sl
          - ripgrep
          - duf
          - whois
          - pwgen
          # XClip for neovim clipboard support
          - xclip
    - name: Install user specified apt packages
      become: yes
      apt:
        state: present
        name: "{{ userAptPackages }}"
    - name: Install user specified snap packages
      command: snap install {{package.pkg}} {{'--classic' if 'classic' in package else ''}}
      become: yes
      loop: "{{ userSnapPackages }}"
      loop_control:
        loop_var: package
    - name: Install copilot CLI
      shell: |
        export NVM_DIR="$HOME/.nvm"
        . "$NVM_DIR/nvm.sh"
        npm install -g @github/copilot
      when: userRoles.copilotCLI
    - name: Install bonded cards deck
      become: yes
      copy:
        src: bonded.svgz
        dest: /usr/share/aisleriot/cards/bonded.svgz
      when: userRoles.aisleriotBonded

  roles:
    - { role: xmonad, when: userRoles.xmonad }
    - { role: dotfiles , when: userRoles.dotfiles }
    - { role: andrewrothstein.starship, when: userRoles.starship }
    - { role: ubuntu-nerd-font, when: userRoles.ubuntuNerdFont }
    - role: markosamuli.nvm
      when: userRoles.nvm
      vars:
        nvm_shell_init: no
    - role: den_is.tools.zoxide
      become: yes
