---
- hosts: localhost
  connection: local
  become_exe: sudo.ws
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - vars/packages.yml
    - vars.json
  tasks:
    - name: Install required tool packages
      apt:
        state: present
        name:
          - git
          - git-delta
          - net-tools
          - curl
          - wget
          - openssh-client
          - moreutils
          - build-essential
          - screen
          - traceroute
          - sl
          - ripgrep
          - duf
          - whois
          - pwgen
          # XClip for neovim clipboard support
          - xclip
    - name: Install user specified apt packages
      become: yes
      apt:
        state: present
        name: "{{ chosen.aptPackages }}"
    - name: Install user specified snap packages
      command: snap install {{package.pkg}} {{'--classic' if 'classic' in package else ''}}
      become: yes
      loop: "{{ snapPackages | selectattr('pkg', 'in', chosen.snapPackages) | list }}"
      loop_control:
        loop_var: package
    - name: Install bonded cards deck
      become: yes
      copy:
        src: bonded.svgz
        dest: /usr/share/aisleriot/cards/bonded.svgz
      when: chosen.roles.aisleriotBonded
    - name: Install jEnv
      git:
        repo: https://github.com/jenv/jenv.git
        dest: ~/.jenv
        clone: yes
        update: yes
      when: chosen.roles.jEnv

  roles:
    - { role: xmonad, when: chosen.roles.xmonad }
    - { role: dotfiles , when: chosen.roles.dotfiles }
    - { role: firefox-from-apt , when: chosen.roles.firefox-from-apt }
    - { role: docker , when: chosen.roles.docker, become: yes }
    - { role: nvm , when: chosen.roles.nvm }
    - { role: andrewrothstein.starship, when: chosen.roles.starship }
    - { role: ubuntu-nerd-font, when: chosen.roles.ubuntuNerdFont }
    - role: den_is.tools.zoxide
      become: yes
