---
- hosts: all
  name: Test playbooks
  vars:
    userChoices: []
    required_packages:
      - git
    installable_configurations:
      - name: starship
        description: Starship shell prompt
      - name: xmonad
        description: XMonad window manager and config
    installable_apt_packages:
      - name: Neovim
        pkg: neovim
      - name: Curl
        pkg: curl
      - name: Ag
        pkg: silversearcher-ag 
      - name: "SSH client and server" 
        pkg: 
          - openssh-client
          - openssh-server
      - name: "Solita VPN prequisites"  
        pkg: 
          - openconnect
          - network-manager-openconnect*
  tasks:
    - name: Choose packages to install
      select_options:
        msg: Choose packages to install
        variable: userChoices
        options: "{{installable_configurations + installable_apt_packages | map(attribute = 'name') | list }}"
      when: (userChoices | length) == 0
    - name: Install required tool packages
      apt:
        name: "{{item}}"
        state: present
      with_items: "{{ required_packages }}"
    - name: Install chosen tool packages
      apt:
        name: "{{item.pkg}}"
        state: present
      when: item.name in userChoices
      with_items: "{{ installable_apt_packages }}"
    - include_tasks: tasks/xmonad.yml
      when: "'xmonad' in userChoices"
    - name: Install starship
      become: yes
      import_role: 
        name: andrewrothstein.starship
      when: "'starship' in userChoices"
