---
- hosts: all
  name: Test playbooks
  tasks:
    - name: Choose packages to install
      select_options:
        msg: What?
        variable: chosenPackages
        options:
          - Bash customizations
    - include_role: 
        name: bash_customizations
      when: "'Bash customizations' in chosenPackages"

