# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
#[ -z "$PS1" ] && return

export $BASH_CONFIG=$HOME/.config/bash
source $BASH_CONFIG/autorun.sh

export EDITOR=vim
export VISUAL=vim
